- hosts: kvm
  become: true
  tasks:
    - name: "Check if qemu image directory does exists"
      stat:
        path: "{{ libvirt_dir }}/images"
      register: imgdir
      tags:
        - imgdircheck

    - fail:
        msg: "{{ libvirt_dir }}/images path doesn't exist"
      when: imgdir.stat.islnk is not defined
      tags:
        - imgdircheck

    - name: "Check if qemu image directory does exists"
      stat:
        path: "{{ libvirt_dir }}/images/{{ img_template }}.qcow2"
      register: imgfile
      tags:
        - imgfilecheck

    - name: Image template copy
      command: " cp -Rv {{ libvirt_dir }}/images/{{ img_template }}.qcow2 {{ libvirt_dir }}/images/{{ item.name }}.qcow2"
      loop: "{{ vm }}"    
      when: imgfilecheck.stat.islnk is not defined

    - name: Copy netplan template script 
      copy:
        content: "sudo sed -i 's/{{ template_address }}/{{ item.net.ip }}/g' /etc/netplan/00-installer-config.yaml && sudo netplan apply"
        dest: "/var/lib/libvirt/images/ubuntu/netplan/{{ item.name }}.netplanedit.sh"
      loop: "{{ vm }}"

    - name: customize the image to set the ip address
      command: "virt-customize  --run /var/lib/libvirt/images/ubuntu/netplan/{{ item.name }}.netplanedit.sh -a  {{ libvirt_dir }}/images/{{ item.name }}.qcow2"
      loop: "{{ vm }}"

    - name: "Check current virtual machines"
      virt:
        command: list_vms
      register: vms

    - name: "{{ item.name }} :: Create virtual machine "
      shell:
         cmd: >-
            virt-install
            --noautoconsole
            --name {{ item.name }}
            --memory {{ item.mem|default('512') }}
            --vcpus  {{ item.cpu|default('1') }}
            --os-variant {{ osvariant }}
            --disk {{ libvirt_dir }}/images/{{ item.name }}.qcow2,device=disk,bus=virtio
            --os-type linux
            --virt-type kvm
            --graphics none
            --network {{ item.net_type|default('network') }}={{ item.net_connector|default('default') }},model=virtio
            --import
      when: item.name not in vms.list_vms
      loop: "{{ vm }}"
      tags:
        - create_vm
