virt-install \
--name ubuntu20.04 \
--ram 4096 \
--disk path=/var/lib/libvirt/images/ubuntu20.04.qcow2,size=20 \
--vcpus 2 \
--os-variant ubuntu20.04 \
--network network=netlab1,model=virtio \
--graphics none \
--console pty,target_type=serial \
--location /var/lib/libvirt/images/ubuntu-20.04.6.iso,kernel=casper/vmlinuz,initrd=casper/initrd \
--extra-args 'console=ttyS0,115200n8 serial' 
