---

# Image url  example
cloudimg_url: https://cloud.centos.org/centos/7/images/CentOS-7-x86_64-GenericCloud-1809.qcow2
#cloudimg_url: https://cloud-images.ubuntu.com/releases/xenial/release/ubuntu-16.04-server-cloudimg-amd64-disk1.img
#cloudimg_url: https://cloud-images.ubuntu.com/bionic/20200407/bionic-server-cloudimg-amd64.img
#cloudimg_url: https://cloud.centos.org/centos/6/images/CentOS-6-x86_64-GenericCloud.qcow2

osvariant: centos7.0
libvirt_dir: /var/lib/libvirt
domain: local.lab
vm_public_key: "{{lookup('file','~/.ssh/id_rsa.pub')}}"
virtual_machines:
  - name: lab1
    cpu: 1
    mem: 512
    disk: 15G
    bridge: bridge0
    net:
      ip: 192.168.15.201
      mask: 255.255.255.0
      gateway: 192.168.15.1
      domain: local.lab
      dns: 8.8.8.8
